__all__ = (
    "ALL_PROXY_ENV_NAMES",
    "DEFAULT_PROXY_PORTS",
    "DEFAULT_TARGET_PORTS",
    "HTTPS_PROXY_ENV_NAMES",
    "HTTP_PROXY_ENV_NAMES",
    "MAX_PORT",
    "MIN_PORT",
    "NO_PROXY_ENV_NAMES",
    "PROXY_URL_HOST_INVALID_REASON",
    "PROXY_URL_HOST_REQUIRED_REASON",
    "PROXY_URL_INVALID_REASON",
    "PROXY_URL_PORT_INVALID_REASON",
    "PROXY_URL_PORT_RANGE_REASON",
    "PROXY_URL_SCHEME_REQUIRED_REASON",
    "PROXY_URL_SCHEME_UNSUPPORTED_REASON",
    "PROXY_URL_SHAPE_UNSUPPORTED_REASON",
    "REQUEST_METHOD_ENV_NAME",
    "SSL_CERT_FILE_ENV_NAMES",
    "SUPPORTED_PROXY_SCHEMES",
)

from types import MappingProxyType


ALL_PROXY_ENV_NAMES = ("all_proxy", "ALL_PROXY")
HTTP_PROXY_ENV_NAMES = ("http_proxy", "HTTP_PROXY")
HTTPS_PROXY_ENV_NAMES = ("https_proxy", "HTTPS_PROXY")
NO_PROXY_ENV_NAMES = ("no_proxy", "NO_PROXY")
REQUEST_METHOD_ENV_NAME = "REQUEST_METHOD"
SSL_CERT_FILE_ENV_NAMES = ("ssl_cert_file", "SSL_CERT_FILE")
MIN_PORT = 1
MAX_PORT = 65535
PROXY_URL_HOST_INVALID_REASON = "host is invalid"
PROXY_URL_HOST_REQUIRED_REASON = "must include a host"
PROXY_URL_INVALID_REASON = "is invalid"
PROXY_URL_PORT_INVALID_REASON = "port is invalid"
PROXY_URL_PORT_RANGE_REASON = f"port must be between {MIN_PORT} and {MAX_PORT}"
PROXY_URL_SCHEME_REQUIRED_REASON = "must include a scheme"
PROXY_URL_SCHEME_UNSUPPORTED_REASON = "scheme must be http"
PROXY_URL_SHAPE_UNSUPPORTED_REASON = "must not include path, query or fragment"
DEFAULT_PROXY_PORTS = MappingProxyType(
    {
        "http": 80,
    },
)
DEFAULT_TARGET_PORTS = MappingProxyType(
    {
        "http": 80,
        "https": 443,
    },
)
SUPPORTED_PROXY_SCHEMES = frozenset(DEFAULT_PROXY_PORTS)
