repos:
  - repo: local
    hooks:
      - id: check-all-position
        name: check __all__ position
        entry: python scripts/check_all_position.py
        language: python
        types: [python]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: pretty-format-json
        args:
          - "--indent=2"
          - "--autofix"
      - id: check-json
      - id: check-yaml
        exclude: ^\.github/
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v4.0.0
    hooks:
      - id: add-trailing-comma

  - repo: https://github.com/crate-ci/typos
    rev: v1.46.1
    hooks:
      - id: typos

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.11.14
    hooks:
      - id: uv-lock

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.12
    hooks:
      - id: ruff-format
      - id: ruff-check
        args: [--fix, --unsafe-fixes]

  - repo: https://github.com/pycqa/flake8
    rev: "7.3.0"
    hooks:
      - id: flake8
        additional_dependencies:
          - wemake-python-styleguide==1.6.2
        files: ^foghttp/.*\.py$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v2.1.0
    hooks:
      - id: mypy
        additional_dependencies:
          - no_implicit_optional
          - orjson>=3.11,<4
          - typing-extensions>=4.3.0,<5
        args: [--config-file=pyproject.toml, --install-types, --non-interactive]
        files: ^foghttp/.*\.pyi?$
