__all__ = ("DEDICATED_RUNTIME", "MAX_RUNTIME_WORKERS", "RUNTIME_WORKERS_ENV", "SHARED_RUNTIME")


DEDICATED_RUNTIME = "dedicated"
MAX_RUNTIME_WORKERS = 32
RUNTIME_WORKERS_ENV = "FOGHTTP_RUNTIME_WORKERS"
SHARED_RUNTIME = "shared"
