__all__ = (
    "ABRUPT_BEFORE_HEADERS_PATH",
    "ABRUPT_DURING_BODY_PATH",
    "BODY_LIMIT",
    "BODY_TOO_LARGE_SIZE",
    "CANCELLATION_STORM_ACTIVE_REQUESTS",
    "CANCELLATION_STORM_PENDING_REQUESTS",
    "CANCELLATION_STORM_REQUESTS",
    "CLOSE_AFTER_BODY_PATH",
    "CONCURRENT_BODY_REQUESTS",
    "CONNECTION_ID_KEY",
    "DELAYED_EOF_UNKNOWN_SIZE_BODY_PATH",
    "DELAYED_PEER_CLOSE_BEFORE_HEADERS_PATH",
    "EXPECTED_BODY_BUDGET_REJECTIONS",
    "EXPECTED_FAILED_REQUESTS_AFTER_FAILURE",
    "EXPECTED_FAILED_REQUESTS_AFTER_RECOVERY",
    "EXPECTED_FIRST_REQUEST_INDEX",
    "EXPECTED_KEEPALIVE_REQUESTS",
    "EXPECTED_REQUESTS_AFTER_FAILURE",
    "EXPECTED_REQUESTS_AFTER_POISONED_FAILURE",
    "EXPECTED_REQUESTS_AFTER_POISONED_RECOVERY",
    "EXPECTED_REQUESTS_AFTER_RECOVERY",
    "EXPECTED_REUSE_ELIGIBLE_BODIES_AFTER_HEALTHY_REUSE",
    "EXPECTED_REUSE_ELIGIBLE_BODIES_AFTER_POISONED_RECOVERY",
    "EXPECTED_SECOND_REQUEST_INDEX",
    "FAULT_DELAY",
    "HEALTHY_BODY",
    "HEALTHY_PATH",
    "INCOMPLETE_BODY_PATH",
    "INVALID_SIZE_SEGMENT",
    "NEGATIVE_SIZE_SEGMENT",
    "PARTIAL_BODY",
    "REQUEST_INDEX_KEY",
    "SLOW_BODY_PATH",
    "SLOW_HEADERS_PATH",
    "TOTAL_TIMEOUT",
)


ABRUPT_BEFORE_HEADERS_PATH = "/abrupt-before-headers"
ABRUPT_DURING_BODY_PATH = "/abrupt-during-body"
DELAYED_EOF_UNKNOWN_SIZE_BODY_PATH = "/delayed-eof-unknown-size-body"
DELAYED_PEER_CLOSE_BEFORE_HEADERS_PATH = "/delayed-peer-close-before-headers"
CLOSE_AFTER_BODY_PATH = "/close-after-body"
HEALTHY_PATH = "/healthy"
INCOMPLETE_BODY_PATH = "/incomplete-body"
INVALID_SIZE_SEGMENT = "not-an-int"
NEGATIVE_SIZE_SEGMENT = "-1"
SLOW_BODY_PATH = "/slow-body"
SLOW_HEADERS_PATH = "/slow-headers"

BODY_LIMIT = 64
BODY_TOO_LARGE_SIZE = 65
CANCELLATION_STORM_ACTIVE_REQUESTS = 3
CANCELLATION_STORM_PENDING_REQUESTS = 5
CANCELLATION_STORM_REQUESTS = CANCELLATION_STORM_ACTIVE_REQUESTS + CANCELLATION_STORM_PENDING_REQUESTS
CONCURRENT_BODY_REQUESTS = 2
EXPECTED_BODY_BUDGET_REJECTIONS = 1
EXPECTED_FAILED_REQUESTS_AFTER_FAILURE = 1
EXPECTED_FAILED_REQUESTS_AFTER_RECOVERY = 1
EXPECTED_FIRST_REQUEST_INDEX = 1
EXPECTED_KEEPALIVE_REQUESTS = 2
EXPECTED_REQUESTS_AFTER_POISONED_FAILURE = 2
EXPECTED_REQUESTS_AFTER_POISONED_RECOVERY = 3
EXPECTED_REQUESTS_AFTER_FAILURE = 1
EXPECTED_REQUESTS_AFTER_RECOVERY = 2
EXPECTED_REUSE_ELIGIBLE_BODIES_AFTER_HEALTHY_REUSE = 2
EXPECTED_REUSE_ELIGIBLE_BODIES_AFTER_POISONED_RECOVERY = 2
EXPECTED_SECOND_REQUEST_INDEX = 2
FAULT_DELAY = 0.25
TOTAL_TIMEOUT = 0.05

CONNECTION_ID_KEY = "connection_id"
REQUEST_INDEX_KEY = "request_index"

HEALTHY_BODY = b"OK"
PARTIAL_BODY = b"partial body"
