__all__ = (
    "ASYNC_BOUNDARY_REQUESTS",
    "GIL_BOUNDARY_SETTLE_DELAY",
    "GIL_PROGRESS_WINDOW",
    "THREAD_JOIN_TIMEOUT",
    "WAIT_TIMEOUT",
)

ASYNC_BOUNDARY_REQUESTS = 12
GIL_BOUNDARY_SETTLE_DELAY = 0.02
GIL_PROGRESS_WINDOW = 0.05
THREAD_JOIN_TIMEOUT = 1.0
WAIT_TIMEOUT = 1.0
