__all__ = (
    "BAD_REQUEST",
    "CLIENT_ERROR_STATUS_CODES",
    "CONFLICT",
    "EXPECTATION_FAILED",
    "FORBIDDEN",
    "GONE",
    "LENGTH_REQUIRED",
    "MAX_CLIENT_ERROR_STATUS_CODE",
    "METHOD_NOT_ALLOWED",
    "MIN_CLIENT_ERROR_STATUS_CODE",
    "MISDIRECTED_REQUEST",
    "NOT_ACCEPTABLE",
    "NOT_FOUND",
    "PAYLOAD_TOO_LARGE",
    "PAYMENT_REQUIRED",
    "PRECONDITION_FAILED",
    "PRECONDITION_REQUIRED",
    "RANGE_NOT_SATISFIABLE",
    "REQUEST_HEADER_FIELDS_TOO_LARGE",
    "REQUEST_TIMEOUT",
    "TOO_EARLY",
    "TOO_MANY_REQUESTS",
    "UNAUTHORIZED",
    "UNAVAILABLE_FOR_LEGAL_REASONS",
    "UNPROCESSABLE_CONTENT",
    "UNSUPPORTED_MEDIA_TYPE",
    "UPGRADE_REQUIRED",
    "URI_TOO_LONG",
)


MIN_CLIENT_ERROR_STATUS_CODE = 400
MAX_CLIENT_ERROR_STATUS_CODE = 499

BAD_REQUEST = 400
UNAUTHORIZED = 401
PAYMENT_REQUIRED = 402
FORBIDDEN = 403
NOT_FOUND = 404
METHOD_NOT_ALLOWED = 405
NOT_ACCEPTABLE = 406
REQUEST_TIMEOUT = 408
CONFLICT = 409
GONE = 410
LENGTH_REQUIRED = 411
PRECONDITION_FAILED = 412
PAYLOAD_TOO_LARGE = 413
URI_TOO_LONG = 414
UNSUPPORTED_MEDIA_TYPE = 415
RANGE_NOT_SATISFIABLE = 416
EXPECTATION_FAILED = 417
MISDIRECTED_REQUEST = 421
UNPROCESSABLE_CONTENT = 422
TOO_EARLY = 425
UPGRADE_REQUIRED = 426
PRECONDITION_REQUIRED = 428
TOO_MANY_REQUESTS = 429
REQUEST_HEADER_FIELDS_TOO_LARGE = 431
UNAVAILABLE_FOR_LEGAL_REASONS = 451

CLIENT_ERROR_STATUS_CODES = (
    BAD_REQUEST,
    UNAUTHORIZED,
    PAYMENT_REQUIRED,
    FORBIDDEN,
    NOT_FOUND,
    METHOD_NOT_ALLOWED,
    NOT_ACCEPTABLE,
    REQUEST_TIMEOUT,
    CONFLICT,
    GONE,
    LENGTH_REQUIRED,
    PRECONDITION_FAILED,
    PAYLOAD_TOO_LARGE,
    URI_TOO_LONG,
    UNSUPPORTED_MEDIA_TYPE,
    RANGE_NOT_SATISFIABLE,
    EXPECTATION_FAILED,
    MISDIRECTED_REQUEST,
    UNPROCESSABLE_CONTENT,
    TOO_EARLY,
    UPGRADE_REQUIRED,
    PRECONDITION_REQUIRED,
    TOO_MANY_REQUESTS,
    REQUEST_HEADER_FIELDS_TOO_LARGE,
    UNAVAILABLE_FOR_LEGAL_REASONS,
)
