__all__ = (
    "FOUND",
    "MAX_REDIRECT_STATUS_CODE",
    "MIN_REDIRECT_STATUS_CODE",
    "MOVED_PERMANENTLY",
    "PERMANENT_REDIRECT",
    "REDIRECT_STATUS_CODES",
    "SEE_OTHER",
    "TEMPORARY_REDIRECT",
)


MIN_REDIRECT_STATUS_CODE = 300
MAX_REDIRECT_STATUS_CODE = 399

MOVED_PERMANENTLY = 301
FOUND = 302
SEE_OTHER = 303
TEMPORARY_REDIRECT = 307
PERMANENT_REDIRECT = 308

REDIRECT_STATUS_CODES = (
    MOVED_PERMANENTLY,
    FOUND,
    SEE_OTHER,
    TEMPORARY_REDIRECT,
    PERMANENT_REDIRECT,
)
