__all__ = (
    "BAD_GATEWAY",
    "GATEWAY_TIMEOUT",
    "HTTP_VERSION_NOT_SUPPORTED",
    "INSUFFICIENT_STORAGE",
    "INTERNAL_SERVER_ERROR",
    "LOOP_DETECTED",
    "MAX_SERVER_ERROR_STATUS_CODE",
    "MIN_SERVER_ERROR_STATUS_CODE",
    "NETWORK_AUTHENTICATION_REQUIRED",
    "NOT_EXTENDED",
    "NOT_IMPLEMENTED",
    "SERVER_ERROR_STATUS_CODES",
    "SERVICE_UNAVAILABLE",
    "VARIANT_ALSO_NEGOTIATES",
)


MIN_SERVER_ERROR_STATUS_CODE = 500
MAX_SERVER_ERROR_STATUS_CODE = 599

INTERNAL_SERVER_ERROR = 500
NOT_IMPLEMENTED = 501
BAD_GATEWAY = 502
SERVICE_UNAVAILABLE = 503
GATEWAY_TIMEOUT = 504
HTTP_VERSION_NOT_SUPPORTED = 505
VARIANT_ALSO_NEGOTIATES = 506
INSUFFICIENT_STORAGE = 507
LOOP_DETECTED = 508
NOT_EXTENDED = 510
NETWORK_AUTHENTICATION_REQUIRED = 511

SERVER_ERROR_STATUS_CODES = (
    INTERNAL_SERVER_ERROR,
    NOT_IMPLEMENTED,
    BAD_GATEWAY,
    SERVICE_UNAVAILABLE,
    GATEWAY_TIMEOUT,
    HTTP_VERSION_NOT_SUPPORTED,
    VARIANT_ALSO_NEGOTIATES,
    INSUFFICIENT_STORAGE,
    LOOP_DETECTED,
    NOT_EXTENDED,
    NETWORK_AUTHENTICATION_REQUIRED,
)
