__all__ = (
    "BODY_BELOW_LIMIT_SIZE",
    "BODY_LIMIT",
    "BODY_TOO_LARGE_SIZE",
    "EMPTY_BODY_SIZE",
    "EXPECTED_TOTAL_REQUESTS_AFTER_RETRY",
    "OK_BODY",
    "REDIRECT_LOCATION_QUERY_PARAM",
    "REDIRECT_STATUS_QUERY_PARAM",
    "REDIRECT_TO_LOCATION_PATH",
    "SLOW_RESPONSE_DELAY",
    "SLOW_RESPONSE_PATH",
    "UNKNOWN_SIZE_BYTES_PATH",
)

BODY_BELOW_LIMIT_SIZE = 7
BODY_LIMIT = 8
BODY_TOO_LARGE_SIZE = 9
EMPTY_BODY_SIZE = 0
EXPECTED_TOTAL_REQUESTS_AFTER_RETRY = 2
OK_BODY = b"OK"
REDIRECT_LOCATION_QUERY_PARAM = "location"
REDIRECT_STATUS_QUERY_PARAM = "status"
REDIRECT_TO_LOCATION_PATH = "/redirect-to-location"
SLOW_RESPONSE_DELAY = 0.25
SLOW_RESPONSE_PATH = "/slow"
UNKNOWN_SIZE_BYTES_PATH = "/unknown-size-bytes"
