__all__ = (
    "OK_BODY",
    "REDIRECT_LOCATION_QUERY_PARAM",
    "REDIRECT_STATUS_QUERY_PARAM",
    "REDIRECT_TO_LOCATION_PATH",
    "SLOW_RESPONSE_DELAY",
    "SLOW_RESPONSE_PATH",
)

OK_BODY = b"OK"
REDIRECT_LOCATION_QUERY_PARAM = "location"
REDIRECT_STATUS_QUERY_PARAM = "status"
REDIRECT_TO_LOCATION_PATH = "/redirect-to-location"
SLOW_RESPONSE_DELAY = 0.25
SLOW_RESPONSE_PATH = "/slow"
