__all__ = (
    "CONNECTION_ID_KEY",
    "EXPECTED_DISTINCT_CONNECTIONS",
    "EXPECTED_FIRST_REQUEST_INDEX",
    "EXPECTED_REUSED_CONNECTIONS",
    "EXPECTED_SECOND_REQUEST_INDEX",
    "EXPECTED_SEQUENTIAL_REQUESTS",
    "KEEPALIVE_PATH",
    "REQUEST_INDEX_KEY",
)


CONNECTION_ID_KEY = "connection_id"
REQUEST_INDEX_KEY = "request_index"

EXPECTED_DISTINCT_CONNECTIONS = 2
EXPECTED_FIRST_REQUEST_INDEX = 1
EXPECTED_REUSED_CONNECTIONS = 1
EXPECTED_SECOND_REQUEST_INDEX = 2
EXPECTED_SEQUENTIAL_REQUESTS = 2

KEEPALIVE_PATH = "/keepalive"
