__all__ = (
    "CONNECTION_ID_KEY",
    "EXPECTED_DISTINCT_CONNECTIONS",
    "EXPECTED_FIRST_REQUEST_INDEX",
    "EXPECTED_REUSED_CONNECTIONS",
    "EXPECTED_SECOND_REQUEST_INDEX",
    "EXPECTED_SEQUENTIAL_REQUESTS",
    "KEEPALIVE_PATH",
    "REDIRECT_PATH_PREFIX",
    "REQUEST_BODY_HEX_KEY",
    "REQUEST_INDEX_KEY",
    "REQUEST_METHOD_KEY",
)


CONNECTION_ID_KEY = "connection_id"
REQUEST_BODY_HEX_KEY = "request_body_hex"
REQUEST_INDEX_KEY = "request_index"
REQUEST_METHOD_KEY = "request_method"

EXPECTED_DISTINCT_CONNECTIONS = 2
EXPECTED_FIRST_REQUEST_INDEX = 1
EXPECTED_REUSED_CONNECTIONS = 1
EXPECTED_SECOND_REQUEST_INDEX = 2
EXPECTED_SEQUENTIAL_REQUESTS = 2

KEEPALIVE_PATH = "/keepalive"
REDIRECT_PATH_PREFIX = "/redirect/"
