__all__ = (
    "EXPECTED_FAILED_REQUESTS",
    "EXPECTED_REQUESTS_AFTER_POOL_WAIT_RECOVERY",
    "EXPECTED_REQUESTS_AFTER_RECOVERY",
    "RECOVERY_TOTAL_TIMEOUT",
    "SENSITIVE_QUERY",
    "SLOW_RESPONSE_DELAY",
    "SLOW_RESPONSE_PATH",
    "SLOW_UPLOAD_BODY_SIZE",
    "SLOW_UPLOAD_HOLD_DELAY",
    "SLOW_UPLOAD_PATH",
    "SLOW_UPLOAD_RECEIVE_BUFFER_SIZE",
    "TOTAL_TIMEOUT",
    "WRITE_TIMEOUT",
    "WRITE_TIMEOUT_TOTAL",
)

EXPECTED_FAILED_REQUESTS = 1
EXPECTED_REQUESTS_AFTER_POOL_WAIT_RECOVERY = 3
EXPECTED_REQUESTS_AFTER_RECOVERY = 2
RECOVERY_TOTAL_TIMEOUT = 1.0
SENSITIVE_QUERY = "?sensitive=do-not-leak"
SLOW_RESPONSE_DELAY = 0.25
SLOW_RESPONSE_PATH = "/slow"
SLOW_UPLOAD_BODY_SIZE = 32 * 1024 * 1024
SLOW_UPLOAD_HOLD_DELAY = 0.5
SLOW_UPLOAD_PATH = "/slow-upload"
SLOW_UPLOAD_RECEIVE_BUFFER_SIZE = 4096
TOTAL_TIMEOUT = 0.05
WRITE_TIMEOUT = 0.05
WRITE_TIMEOUT_TOTAL = 2.0
