__all__ = (
    "EXPECTED_FAILED_REQUESTS",
    "EXPECTED_REQUESTS_AFTER_POOL_WAIT_RECOVERY",
    "EXPECTED_REQUESTS_AFTER_RECOVERY",
    "RECOVERY_TOTAL_TIMEOUT",
    "SENSITIVE_QUERY",
    "SLOW_RESPONSE_DELAY",
    "SLOW_RESPONSE_PATH",
    "TOTAL_TIMEOUT",
)

EXPECTED_FAILED_REQUESTS = 1
EXPECTED_REQUESTS_AFTER_POOL_WAIT_RECOVERY = 3
EXPECTED_REQUESTS_AFTER_RECOVERY = 2
RECOVERY_TOTAL_TIMEOUT = 1.0
SENSITIVE_QUERY = "?sensitive=do-not-leak"
SLOW_RESPONSE_DELAY = 0.25
SLOW_RESPONSE_PATH = "/slow"
TOTAL_TIMEOUT = 0.05
