from collections.abc import Sequence
from typing import TypeAlias

HeaderPairs: TypeAlias = Sequence[tuple[str, str]]

class FogHttpError(Exception): ...
class FogHttpTimeoutError(FogHttpError): ...

class RawRequestInfo:
    @property
    def method(self) -> str: ...
    @property
    def url(self) -> str: ...
    @property
    def headers(self) -> HeaderPairs: ...

class RawResponse:
    @property
    def status_code(self) -> int: ...
    @property
    def headers(self) -> HeaderPairs: ...
    @property
    def content(self) -> bytes: ...
    @property
    def url(self) -> str: ...
    @property
    def request(self) -> RawRequestInfo: ...
    @property
    def http_version(self) -> str: ...
    @property
    def elapsed(self) -> float: ...
    @property
    def history(self) -> tuple[RawResponse, ...]: ...

class RawStats:
    @property
    def active_connections(self) -> int: ...
    @property
    def idle_connections(self) -> int: ...
    @property
    def pending_acquires(self) -> int: ...
    @property
    def total_requests(self) -> int: ...
    @property
    def failed_requests(self) -> int: ...
    @property
    def reused_connections(self) -> int: ...
    @property
    def opened_connections(self) -> int: ...
    @property
    def closed_connections(self) -> int: ...
    @property
    def pool_timeouts(self) -> int: ...

class RawUrl:
    def __init__(self, url: str) -> None: ...
    @property
    def value(self) -> str: ...
    @property
    def scheme(self) -> str: ...
    @property
    def host(self) -> str: ...
    @property
    def port(self) -> int: ...
    @property
    def path(self) -> str: ...
    @property
    def query(self) -> str: ...
    @property
    def fragment(self) -> str: ...
    @property
    def origin(self) -> str: ...
    def join(self, location: str) -> RawUrl: ...
    def is_same_origin(self, other: RawUrl) -> bool: ...

class RawClient:
    def __init__(
        self,
        max_connections: int,
        max_connections_per_host: int,
        idle_timeout: float,
        keepalive: bool,
        connect_timeout: float,
        follow_redirects: bool,
        max_redirects: int,
        trust_env: bool,
    ) -> None: ...
    def request(
        self,
        method: str,
        url: str,
        headers: HeaderPairs,
        body: bytes | None,
        connect_timeout: float,
        total_timeout: float,
    ) -> RawResponse: ...
    async def request_async(
        self,
        method: str,
        url: str,
        headers: HeaderPairs,
        body: bytes | None,
        connect_timeout: float,
        total_timeout: float,
    ) -> RawResponse: ...
    def stats(self) -> RawStats: ...
