from collections.abc import Mapping

class FogHttpError(Exception): ...
class FogHttpTimeoutError(FogHttpError): ...

class RawResponse:
    @property
    def status_code(self) -> int: ...
    @property
    def headers(self) -> Mapping[str, str]: ...
    @property
    def content(self) -> bytes: ...
    @property
    def url(self) -> str: ...
    @property
    def http_version(self) -> str: ...
    @property
    def elapsed(self) -> float: ...

class RawStats:
    @property
    def active_connections(self) -> int: ...
    @property
    def idle_connections(self) -> int: ...
    @property
    def pending_acquires(self) -> int: ...
    @property
    def total_requests(self) -> int: ...
    @property
    def failed_requests(self) -> int: ...
    @property
    def reused_connections(self) -> int: ...
    @property
    def opened_connections(self) -> int: ...
    @property
    def closed_connections(self) -> int: ...
    @property
    def pool_timeouts(self) -> int: ...

class RawClient:
    def __init__(
        self,
        max_connections: int,
        max_connections_per_host: int,
        idle_timeout: float,
        keepalive: bool,
        connect_timeout: float,
        follow_redirects: bool,
        trust_env: bool,
    ) -> None: ...
    def request(
        self,
        method: str,
        url: str,
        headers: dict[str, str],
        body: bytes | None,
        connect_timeout: float,
        total_timeout: float,
    ) -> RawResponse: ...
    def stats(self) -> RawStats: ...
