__all__ = (
    "SYNTHETIC_TELEMETRY_SNAPSHOT_SEQUENCE",
    "TELEMETRY_EVENT_SCHEMA_VERSION",
    "TELEMETRY_SNAPSHOT_SCHEMA_VERSION",
)


SYNTHETIC_TELEMETRY_SNAPSHOT_SEQUENCE = 0
TELEMETRY_EVENT_SCHEMA_VERSION = 1
TELEMETRY_SNAPSHOT_SCHEMA_VERSION = 1
