__all__ = (
    "EXPECTED_FAILED_REQUESTS",
    "EXPECTED_REQUESTS_AFTER_FAILURE",
    "EXPECTED_REQUESTS_AFTER_RECOVERY",
    "INVALID_URL",
    "MALFORMED_RESPONSE_PATH",
    "MID_RESPONSE_CLOSE_PATH",
    "NETWORK_ERROR_TIMEOUTS",
)

import foghttp


EXPECTED_FAILED_REQUESTS = 1
EXPECTED_REQUESTS_AFTER_FAILURE = 1
EXPECTED_REQUESTS_AFTER_RECOVERY = 2
INVALID_URL = "http://"
MALFORMED_RESPONSE_PATH = "/malformed-response"
MID_RESPONSE_CLOSE_PATH = "/mid-response-close"
NETWORK_ERROR_TIMEOUTS = foghttp.Timeouts(connect=0.2, pool=0.2, total=1.0)
